title: 滋賀県彦根市
description: 滋賀県彦根市内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vTpnyop0om3Wx5SKN6rHpph0hHaFy_hVCjcjNqBMdl31kmAxVPjoLpOQY7I7X_B90m2W2wrz2JcW_MQ/pub?gid=0&single=true&output=csv
repository: https://github.com/iemeshi/hikone.iemeshi.jp/
